name: Pipeline DevOps - Build App

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar código
      uses: actions/checkout@v3

    - name: Construir imagen Docker
      run: docker build -t devops-training-app .

    - name: Ejecutar contenedor
      run: docker run -d -p 5000:5000 devops-training-app
